#+ endpoint_in_url: False
#+ pagination: 50
#+ transform: {
#+     "label": "?personLabel",
#+     "uri": "?person",
#+     "$anchor": "uri"
#+   }

PREFIX  bds:  <http://www.bigdata.com/rdf/search#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT ?person ?personLabel
WHERE {
    ?person a crm:E21_Person .
    ?person rdfs:label ?personLabel
    SERVICE <http://www.bigdata.com/rdf/search#search> { 
        ?personLabel bds:search ?_name_de
    }
}
ORDER BY DESC(?person)
