#+ endpoint_in_url: False
#+ transform: {
#+     "label": "?personLabel",
#+     "uri": "?person"
#+   }

PREFIX  bds:  <http://www.bigdata.com/rdf/search#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?person ?personLabel
WHERE {
    ?person a crm:E21_Person .
    ?person rdfs:label ?personLabel .
    ?birth crm:P98_brought_into_life ?person .
    ?birth  crm:P4_has_time-span ?date .
    ?date crm:P82a_begin_of_the_begin ?begin_of_birth .
      FILTER (?begin_of_birth > "?__birth_not_before_xsd_date")
      #FILTER (?begin_of_birth > "1800-01-01"^^xsd:date)
      # ^^ works with hard-coded date but not parsing date ??
    

 
	SERVICE <http://www.bigdata.com/rdf/search#search> { 
        ?personLabel bds:search ?_name_de
    }
    
}





